server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://frontend:80"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
        - id: comment-service
          uri: http://comment-service:3000
          predicates:
            - Path=/api/comments/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/TaskFlow}/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
