spring:
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
